//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_VR3_GRISHIN.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int idCustomer { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string CustomerNumber { get; set; }
        public int idOrder { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
